"""
Central callback registry.
All features must enter from inline callbacks to preserve Inline-First UX.
"""

MENU_HOME = "menu_home"
MENU_REGISTER = "menu_register"
MENU_PROFILE = "menu_profile"
MENU_GRADES = "menu_grades"
MENU_REP_PANEL = "menu_rep_panel"
MENU_REP_PENDING = "menu_rep_pending"
MENU_REP_IMPORT_GRADES = "menu_rep_import_grades"
MENU_REP_BROADCAST = "menu_rep_broadcast"
MENU_REP_FORMS = "menu_rep_forms"
MENU_REP_FORM_CREATE = "menu_rep_form_create"
MENU_REP_FORM_LIST = "menu_rep_form_list"
MENU_REP_SCHEDULES = "menu_rep_schedules"
MENU_ADMIN_PANEL = "menu_admin_panel"
MENU_ADMIN_STUDENTS = "menu_admin_students"
MENU_ADMIN_REMOVE = "menu_admin_remove"
MENU_ADMIN_REMOVE_DIRECT = "menu_admin_remove_direct"
MENU_CANCEL = "menu_cancel"

PREFIX_PAGE = "page:"
PREFIX_VERIFY_APPROVE = "verify_approve:"
PREFIX_VERIFY_REJECT = "verify_reject:"
PREFIX_FORM_VIEW = "form_view:"
PREFIX_FORM_EXPORT = "form_export:"
PREFIX_FORM_CLOSE = "form_close:"
PREFIX_FORM_REOPEN = "form_reopen:"
PREFIX_FORM_DUPLICATE = "form_duplicate:"
PREFIX_FORM_REMIND = "form_remind:"
PREFIX_FORM_REMOVE_SUBMISSION = "form_remove_submission:"
PREFIX_FORM_MANUAL_ADD = "form_manual_add:"
PREFIX_FORM_SEARCH = "form_search:"
PREFIX_FORM_JOIN = "form_join:"
PREFIX_QUESTION_TYPE = "question_type:"
PREFIX_REQUIRED = "question_required:"
PREFIX_ADD_ANOTHER_QUESTION = "add_another_question:"
PREFIX_CHOICE_PICK = "choice_pick:"
PREFIX_CHECKBOX_TOGGLE = "checkbox_toggle:"
PREFIX_CHECKBOX_DONE = "checkbox_done:"
PREFIX_SCHEDULE_FORM = "schedule_form:"
PREFIX_SCHEDULE_CANCEL = "schedule_cancel:"
PREFIX_SCHEDULE_VIEW = "schedule_view:"
PREFIX_SCHEDULE_DEACTIVATE = "schedule_deactivate:"
PREFIX_ADMIN_REMOVE_SELECT = "admin_remove_select:"
PREFIX_ADMIN_REMOVE_CONFIRM = "admin_remove_confirm:"
PREFIX_ADMIN_REMOVE_CANCEL = "admin_remove_cancel:"
PREFIX_DATE_PICKER = "datepick:"
